name: Links checker
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:

  link-checker:
    name: "Links checker"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3.1.0

      - name: Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.14
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
